crm/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager

from .config import Config

# database handle
db = SQLAlchemy(session_options={"autoflush": False})

# encryptor handle
bcrypt = Bcrypt()

# manage user login
login_manager = LoginManager()

# function name of the login route that
# tells the path which facilitates authentication
login_manager.login_view = 'users.login'


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    app.url_map.strict_slashes = False
    app.jinja_env.globals.update(zip=zip)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)

    # include the routes
    # from crm import routes
    from crm.main.routes import main
    from crm.users.routes import users
    from crm.leads.routes import leads
    from crm.accounts.routes import accounts
    from crm.contacts.routes import contacts
    from crm.deals.routes import deals
    from crm.settings.routes import settings
    from crm.reports.routes import reports

    # register routes with blueprint
    app.register_blueprint(main)
    app.register_blueprint(users)
    app.register_blueprint(settings)
    app.register_blueprint(leads)
    app.register_blueprint(accounts)
    app.register_blueprint(contacts)
    app.register_blueprint(deals)
    app.register_blueprint(reports)

    return app

crm/leads/routes.py
import pandas as pd
from sqlalchemy import or_
from wtforms import Label

from flask import Blueprint, session, Response
from flask_login import current_user, login_required
from flask import render_template, flash, url_for, redirect, request

from crm import db
from .models import Lead
from crm.common.paginate import Paginate
from crm.common.filters import CommonFilters
from .filters import set_date_filters, set_source, set_status
from .forms import NewLead, ImportLeads, ConvertLead, \
    FilterLeads, BulkOwnerAssign, BulkLeadSourceAssign, BulkLeadStatusAssign, BulkDelete

from crm.rbac import check_access, is_admin

leads = Blueprint('leads', __name__)


def reset_lead_filters():
    if 'lead_owner' in session:
        session.pop('lead_owner', None)
    if 'lead_search' in session:
        session.pop('lead_search', None)
    if 'lead_date_created' in session:
        session.pop('lead_date_created', None)
    if 'lead_source' in session:
        session.pop('lead_source', None)
    if 'lead_status' in session:
        session.pop('lead_status', None)


@leads.route("/leads", methods=['GET', 'POST'])
@login_required
@check_access('leads', 'view')
def get_leads_view():
    filters = FilterLeads()
    search = CommonFilters.set_search(filters, 'lead_search')
    owner = CommonFilters.set_owner(filters, 'Lead', 'lead_owner')
    advanced_filters = set_date_filters(filters, 'lead_date_created')
    source_filter = set_source(filters, 'lead_source')
    status_filter = set_status(filters, 'lead_status')

    query = Lead.query \
        .filter(or_(
            Lead.title.ilike(f'%{search}'),
            Lead.first_name.ilike(f'%{search}'),
            Lead.last_name.ilike(f'%{search}'),
            Lead.email.ilike(f'%{search}'),
            Lead.company_name.ilike(f'%{search}'),
            Lead.phone.ilike(f'%{search}'),
            Lead.mobile.ilike(f'%{search}'),
        ) if search else True) \
        .filter(source_filter) \
        .filter(status_filter) \
        .filter(owner) \
        .filter(advanced_filters) \
        .order_by(Lead.date_created.desc())

    bulk_form = {
        'owner': BulkOwnerAssign(),
        'lead_source': BulkLeadSourceAssign(),
        'lead_status': BulkLeadStatusAssign(),
        'delete': BulkDelete()
    }

    return render_template("leads/leads_list.html", title="Leads View",
                           leads=Paginate(query), filters=filters, bulk_form=bulk_form)


@leads.route("/leads/new", methods=['GET', 'POST'])
@login_required
@check_access('leads', 'create')
def new_lead():
    form = NewLead()
    if request.method == 'POST':
        if form.validate_on_submit():
            lead = Lead(title=form.title.data,
                        first_name=form.first_name.data, last_name=form.last_name.data,
                        email=form.email.data, company_name=form.company.data,
                        address_line=form.address_line.data, addr_state=form.addr_state.data,
                        addr_city=form.addr_city.data, post_code=form.post_code.data,
                        country=form.country.data, source=form.lead_source.data,
                        status=form.lead_status.data, notes=form.notes.data)

            if current_user.role.name == 'admin':
                lead.owner = form.assignees.data
            else:
                lead.owner = current_user

            db.session.add(lead)
            db.session.commit()
            flash('New lead has been successfully created!', 'success')
            return redirect(url_for('leads.get_leads_view'))
        else:
            for error in form.errors:
                print(error)
            flash('Your form has errors! Please check the fields', 'danger')
    return render_template("leads/new_lead.html", title="New Lead", form=form)


@leads.route("/leads/edit/<int:lead_id>", methods=['GET', 'POST'])
@login_required
@check_access('leads', 'update')
def update_lead(lead_id):
    lead = Lead.get_by_id(lead_id)
    if not lead:
        return redirect(url_for('leads.get_leads_view'))

    form = NewLead()
    if request.method == 'POST':
        if form.validate_on_submit():
            lead.title = form.title.data
            lead.first_name = form.first_name.data
            lead.last_name = form.last_name.data
            lead.email = form.email.data
            lead.company_name = form.company.data
            lead.phone = form.phone.data
            lead.mobile = form.mobile.data
            lead.address_line = form.address_line.data
            lead.addr_state = form.addr_state.data
            lead.addr_city = form.addr_city.data
            lead.post_code = form.post_code.data
            lead.country = form.country.data
            lead.owner = form.assignees.data
            lead.source = form.lead_source.data
            lead.status = form.lead_status.data
            lead.notes = form.notes.data
            db.session.commit()
            flash('The lead has been successfully updated', 'success')
            return redirect(url_for('leads.get_lead_view', lead_id=lead.id))
        else:
            print(form.errors)
            flash('User update failed! Form has errors', 'danger')
    elif request.method == 'GET':
        form.title.data = lead.title
        form.first_name.data = lead.first_name
        form.last_name.data = lead.last_name
        form.email.data = lead.email
        form.company.data = lead.company_name
        form.phone.data = lead.phone
        form.mobile.data = lead.mobile
        form.address_line.data = lead.address_line
        form.addr_state.data = lead.addr_state
        form.addr_city.data = lead.addr_city
        form.post_code.data = lead.post_code
        form.country.data = lead.country
        form.assignees.data = lead.owner
        form.lead_source.data = lead.source
        form.lead_status.data = lead.status
        form.notes.data = lead.notes
        form.submit.label = Label('update_lead', 'Update Lead')
    return render_template("leads/new_lead.html", title="Update Lead", form=form)


@leads.route("/leads/<int:lead_id>")
@login_required
@check_access('leads', 'view')
def get_lead_view(lead_id):
    lead = Lead.query.filter_by(id=lead_id).first()
    return render_template("leads/lead_view.html", title="View Lead", lead=lead)


@leads.route("/leads/convert/<int:lead_id>", methods=['GET', 'POST'])
@login_required
@check_access('leads', 'view')
@check_access('accounts', 'create')
@check_access('contacts', 'create')
@check_access('deals', 'create')
def convert_lead(lead_id):
    lead = Lead.query.filter_by(id=lead_id).first()
    form = ConvertLead()
    form.account_name.data = lead.company_name
    form.account_email.data = lead.email

    if request.method == 'POST':
        if form.validate_on_submit():
            if form.use_account_information.data and form.use_contact_information.data:
                # create both account and contact

                pass
            elif form.use_account_information.data and not form.use_contact_information.data:
                # create account only (and contact if chosen from dropdown)
                if not form.account_name.data:
                    form.account_name.errors = ['Please enter account name']
                if not form.account_name.data:
                    form.account_email.errors = ['Please enter account email']
            elif not form.use_account_information.data and form.use_contact_information.data:
                pass
                # create contact only (account dropdown must be selected)
            elif not form.use_account_information.data and not form.use_contact_information.data:
                # account must be selected in dropdown (and create contact if selected in dropdown)
                if not form.accounts.data:
                    form.accounts.errors = ['Please select an account']
                pass

            flash('Leads has been successfully converted!', 'success')
        else:
            flash('Your form has errors! Please check the fields', 'danger')
    else:
        form.title.data = lead.title
    return render_template("leads/lead_convert.html", title="Convert Lead", lead=lead, form=form)


@leads.route("/leads/import", methods=['GET', 'POST'])
@login_required
@is_admin
def import_bulk_leads():
    form = ImportLeads()
    if request.method == 'POST':
        ind = 0
        if form.validate_on_submit():
            data = pd.read_csv(form.csv_file.data)

            for _, row in data.iterrows():
                lead = Lead(first_name=row['first_name'], last_name=row['last_name'],
                            email=row['email'], company_name=row['company_name'])
                lead.owner = current_user
                if form.lead_source.data:
                    lead.source = form.lead_source.data
                db.session.add(lead)
                ind = ind + 1

            db.session.commit()
            flash(f'{ind} new lead(s) has been successfully imported!', 'success')
        else:
            flash('Your form has errors! Please check the fields', 'danger')
    return render_template("leads/leads_import.html", title="Import Leads", form=form)


@leads.route("/leads/reset_filters")
@login_required
@check_access('leads', 'view')
def reset_filters():
    reset_lead_filters()
    return redirect(url_for('leads.get_leads_view'))


@leads.route("/leads/bulk_owner_assign", methods=['POST'])
@login_required
@is_admin
def bulk_owner_assign():
    form = BulkOwnerAssign()
    if request.method == 'POST':
        if form.validate_on_submit():
            if form.owners_list.data:
                ids = [int(x) for x in request.form['leads_owner'].split(',')]
                Lead.query\
                    .filter(Lead.id.in_(ids))\
                    .update({
                        Lead.owner_id: form.owners_list.data.id
                    }, synchronize_session=False)
                db.session.commit()

crm/reports/routes.py
from flask import Blueprint
from flask_login import current_user, login_required
from flask import render_template
from sqlalchemy import func, text
from crm.deals.models import Deal, DealStage
from crm.accounts.models import Account
from crm.users.models import User
from crm.rbac import is_admin

from functools import reduce

reports = Blueprint('reports', __name__)


@reports.route("/reports/deals")
@login_required
def deal_reports():
    return render_template("reports/reports.html", title="Reports")


@reports.route("/reports/deal_stages")
@login_required
def deal_stages():
    if current_user.role.name == 'admin':
        query = Deal.query \
            .with_entities(
                DealStage.stage_name.label('stage_name'),
                func.sum(Deal.expected_close_price).label('total_price'),
                func.count(Deal.id).label('total_count')
            ) \
            .join(Deal.deal_stage) \
            .group_by(DealStage.stage_name) \
            .order_by(text('total_price DESC'))
    else:
        query = Deal.query \
            .with_entities(
                DealStage.stage_name.label('stage_name'),
                func.sum(Deal.expected_close_price).label('total_price'),
                func.count(Deal.id).label('total_count')
            ) \
            .join(Deal.deal_stage) \
            .group_by(DealStage.stage_name, Deal.owner_id) \
            .having(Deal.owner_id == current_user.id) \
            .order_by(text('total_price DESC'))

    return render_template("reports/deals_stages.html",
                           title="Reports: Deal Stages", deals=query.all())


@reports.route("/reports/deals_closed")
@login_required
def deals_closed():
    if current_user.role.name == 'admin':
        query = Deal.query \
            .with_entities(
                Account.name.label('account_name'),
                DealStage.stage_name.label('stage_name'),
                func.sum(Deal.expected_close_price).label('total_price'),
                func.count(Deal.id).label('total_count')
            ) \
            .join(Deal.account, Deal.deal_stage) \
            .group_by(Account.name, DealStage.stage_name) \
            .order_by(text('stage_name'))
    else:
        query = Deal.query \
            .with_entities(
                Account.name.label('account_name'),
                DealStage.stage_name.label('stage_name'),
                func.sum(Deal.expected_close_price).label('total_price'),
                func.count(Deal.id).label('total_count')
            ) \
            .join(Deal.account, Deal.deal_stage) \
            .group_by(Account.name, DealStage.stage_name, Deal.owner_id) \
            .having(Deal.owner_id == current_user.id) \
            .order_by(text('stage_name'))

    stages = []
    data = []
    rows = query.all()
    if len(rows) > 0:
        for d in rows:
            if d[1] not in stages:
                stages.append(d[1])
                data.append({
                    'stage_name': d[1],
                    'accounts_count': len([x[1] for x in rows if x[1] == d[1]]),
                    'rows': [(x[0], x[2], x[3]) for x in rows if x[1] == d[1]]
                })

    return render_template("reports/deals_closed.html",
                           title="Reports: Deals Stages by Accounts", deals=data)


def get_users_deals():
    users_list = Deal.query \
        .with_entities(
            Deal.owner_id.label('owner'),
            User.first_name,
            User.last_name,
            DealStage.stage_name,
            func.sum(Deal.expected_close_price).label('total_price')
        ) \
        .filter(DealStage.stage_name.in_(['Closed - Won', 'Closed - Lost'])) \
        .join(Deal.owner, Deal.deal_stage) \
        .group_by(Deal.owner_id, User.first_name, User.last_name, DealStage.stage_name) \
        .order_by(text('owner'))

    won_list = [x for x in users_list.all() if x.stage_name == 'Closed - Won']
    lost_list = [x for x in users_list.all() if x.stage_name == 'Closed - Lost']
    return won_list, lost_list


@reports.route("/reports/deal_stage_by_users")
@login_required
@is_admin
def deal_stage_by_users():
    query = Deal.query \
        .with_entities(
            Deal.owner_id.label('owner'),
            User.first_name,
            User.last_name,
            DealStage.stage_name.label('stage_name'),
            func.sum(Deal.expected_close_price).label('total_price'),
            func.count(Deal.id).label('total_count')
        ) \
        .join(Deal.owner, Deal.deal_stage) \
        .group_by(Deal.owner_id, User.first_name, User.last_name, DealStage.stage_name) \
        .order_by(text('owner'))

    users = []
    data = []
    rows = query.all()
    if len(rows) > 0:
        for d in rows:
            if d[0] not in users:
                users.append(d[0])
                data.append({
                    'owner': f'{d[1]} {d[2]}',
                    'count': len([x[3] for x in rows if x[0] == d[0]]),
                    'rows': [(x[3], x[4], x[5]) for x in rows if x[0] == d[0]],
                    'total_cost': reduce(lambda a, b: a + b, [x[4] for x in rows if x[0] == d[0]]),
                    'total_qty': reduce(lambda a, b: a + b, [x[5] for x in rows if x[0] == d[0]])
                })

    return render_template("reports/deals_stage_by_users.html",
                           title="Reports: Deal Stages by Users",
                           deals=data,
                           deals_closed=get_users_deals())


@reports.route("/reports/deal_closed_by_date")
@login_required
def deal_closed_by_date():
    query = Deal.query \
        .with_entities(
            Deal.owner_id.label('owner'),
            User.first_name,
            User.last_name,
            DealStage.stage_name,
            Deal.expected_close_price.label('total_price')
        ) \
        .filter(DealStage.stage_name.in_(['Closed - Won', 'Closed - Lost'])) \
        .join(Deal.owner, Deal.deal_stage) \
        .group_by(
            Deal.owner_id,
            User.first_name,
            User.last_name,
            DealStage.stage_name,
            Deal.expected_close_date,
            Deal.expected_close_price) \
        .order_by(text('owner'))

    return render_template("reports/deals_closed_by_time.html",
                           title="Reports: Deal Stages by Users",
                           deals=data,
                           deals_closed=get_users_deals())

crm/templates/reports/deals_closed.html
{% extends "layout.html" %}
    {% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2 class="h4">{% if title %}{{title}}{% else %}No Title{% endif %}</h2>
        <div class="btn-toolbar mb-2 mb-md-0">
            <a class="btn btn btn-sm btn-outline-primary" role="button" href="{{ url_for('reports.deal_reports') }}">
                <span data-feather="arrow-left"></span>
                  Back to Deal Reports
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-12">

    {% if deals|length > 0 %}
        <div class="table-responsive">
            <table class="table table-striped table-hover fixed-layout-table">
              <thead class="thead-light">
                <tr>
                    <th width="150" scope="col">Deal Stage</th>
                    <th width="150" scope="col">Account Name</th>
                    <th width="150" scope="col">Total Cost</th>
                    <th width="150" scope="col">Deals Count</th>
                </tr>
              </thead>
              <tbody>
                {% for deal in deals %}
                <tr>
                    <td colspan="4">{{ deal.stage_name }}
                        <span class="badge badge-info">{{ deal.accounts_count }} accounts</span>
                    </td>
                </tr>
                    {% for item in deal.rows %}
                        <tr>
                            <td></td>
                            <td>{{ item[0] }}</td>
                            <td>{{ "$ {:,.2f}".format(item[1]) }}</td>
                            <td>{{ item[2] }}</td>
                        </tr>
                    {% endfor %}
                {% endfor %}
              </tbody>
            </table>
        </div>
    {% else %}
        <div class="container text-center pt-4">
            <div><span data-feather="eye-off"></span></div>
            <p>No deal stage records found.</p>
        </div>
    {% endif %}
        </div>
    </div>
    {% endblock %}

crm/templates/reports/deals_stage_by_users.html
{% extends "layout.html" %}
    {% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2 class="h4">{% if title %}{{title}}{% else %}No Title{% endif %}</h2>
        <div class="btn-toolbar mb-2 mb-md-0">
            <a class="btn btn btn-sm btn-outline-primary" role="button" href="{{ url_for('reports.deal_reports') }}">
                <span data-feather="arrow-left"></span>
                  Back to Deal Reports
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-12 mb-4">
            <canvas id="deals_closed_bg" class="seg_chart_1" width="600" height="300"></canvas>
        </div>
    </div>

    <div class="row">
        <div class="col-12">

    {% if deals|length > 0 %}
        <div class="table-responsive">
            <table class="table table-striped table-hover fixed-layout-table">
              <thead class="thead-light">
                <tr>
                    <th width="150" scope="col">User</th>
                    <th width="150" scope="col">Deal Stage</th>
                    <th width="150" scope="col">Total Cost</th>
                    <th width="150" scope="col">Deals Count</th>
                </tr>
              </thead>
              <tbody>
                {% for deal in deals %}
                <tr>
                    <th colspan="4">{{ deal.owner }}</th>
                </tr>
                    {% for item in deal.rows %}
                        <tr>
                            <td></td>
                            <td>{{ item[0] }}</td>
                            <td>{{ "$ {:,.2f}".format(item[1]) }}</td>
                            <td>{{ item[2] }}</td>
                        </tr>
                    {% endfor %}
                <tr>
                    <th>Total</th>
                    <th></th>
                    <th>{{ "$ {:,.2f}".format(deal.total_cost) }}</th>
                    <th>{{ "{:,}".format(deal.total_qty) }}</th>
                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>
    {% else %}
        <div class="container text-center pt-4">
            <div><span data-feather="eye-off"></span></div>
            <p>No deal stage records found.</p>
        </div>
    {% endif %}
        </div>
    </div>
<script src="{{ url_for('static', filename='scripts/reports/deal_closed_by_user_reports.js') }}"></script>
<script>
    $(document).ready(function() {
        var labels = [];
        var data_won = [];
        var data_lost = [];

        {% for deal in deals_closed[0] %}
            labels.push('{{ deal.first_name }} {{ deal.last_name }}');
            data_won.push({{ deal.total_price }});
        {% endfor %}

        {% for deal in deals_closed[1] %}
            data_lost.push({{ deal.total_price }});
        {% endfor %}

        plot_deal_closed_report_price_bar_graph('deals_closed_bg', labels, data_won, data_lost);
    });
</script>
    {% endblock %}

crm/templates/reports/deals_stages.html
{% extends "layout.html" %}
    {% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2 class="h4">{% if title %}{{title}}{% else %}No Title{% endif %}</h2>
        <div class="btn-toolbar mb-2 mb-md-0">
            <a class="btn btn btn-sm btn-outline-primary" role="button" href="{{ url_for('reports.deal_reports') }}">
                <span data-feather="arrow-left"></span>
                  Back to Deal Reports
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-6 mb-4">
            <div class="btn-group" role="group" aria-label="Basic example">
              <button type="button" id="ds_price" class="btn btn-sm btn-outline-secondary">Price</button>
              <button type="button" id="ds_count" class="btn btn-sm btn-outline-secondary">Volume</button>
            </div>
            <canvas id="myChart1" class="seg_chart_1" width="400" height="300"></canvas>
            <canvas id="myChart2" class="seg_chart_2" style="display: none;" width="400" height="300"></canvas>
        </div>
        <div class="col-6 mb-4">
            <canvas id="myChart3" class="seg_chart_1" width="400" height="300"></canvas>
        </div>
    </div>

    <div class="row">
        <div class="col-9">

    {% if deals|length > 0 %}
        <div class="table-responsive">
            <table class="table table-striped table-hover fixed-layout-table">
              <thead class="thead-light">
                <tr>
                    <th width="150" scope="col">Deal Stage</th>
                    <th width="150" scope="col">Total Cost</th>
                    <th width="150" scope="col">Deals Count</th>
                </tr>
              </thead>
              <tbody>
                {% for deal in deals %}
                <tr>
                      <td>{{ deal.stage_name }}</td>
                      <td>{{ "$ {:,.2f}".format(deal.total_price) }}</td>
                    <td><span class="badge badge-info">{{ deal.total_count }}</span></td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>
    {% else %}
        <div class="container text-center pt-4">
            <div><span data-feather="eye-off"></span></div>
            <p>No deal stage records found.</p>
        </div>
    {% endif %}
        </div>
    </div>
<script src="{{ url_for('static', filename='scripts/reports/deal_stage_reports.js') }}"></script>
    <script>
            $(document).ready(function() {
                var label_arr = [];
                var data_arr = [];
                var data_arr1 = [];

                {% for deal in deals %}
                    label_arr.push('{{ deal.stage_name }}');
                    data_arr.push({{ deal.total_price }});
                    data_arr1.push({{ deal.total_count }});
                {% endfor %}

                plot_deal_stage_report_price_bar_graph(label_arr, data_arr);
                plot_deal_stage_report_count_bar_graph(label_arr, data_arr1);
                plot_deal_stage_report_price_pie_chart(label_arr, data_arr);

                $('#ds_price')
                    .removeClass('btn-outline-secondary')
                    .addClass('btn-secondary');

                $('#ds_price').on('click', function() {
                    $('#myChart1').css('display', 'block');
                    $('#myChart2').css('display', 'none');

                    $('#ds_price')
                        .removeClass('btn-outline-secondary')
                        .addClass('btn-secondary');

                    $('#ds_count')
                        .removeClass('btn-secondary')
                        .addClass('btn-outline-secondary');
                });

                 $('#ds_count').on('click', function() {
                    $('#myChart1').css('display', 'none');
                    $('#myChart2').css('display', 'block');

                    $('#ds_price')
                        .removeClass('btn-secondary')
                        .addClass('btn-outline-secondary');

                    $('#ds_count')
                        .removeClass('btn-outline-secondary')
                        .addClass('btn-secondary');
                 });
            });
    </script>
    {% endblock %}

crm/templates/reports/reports.html
{% extends "layout.html" %}
    {% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2 class="h4">{% if title %}{{title}}{% else %}No Title{% endif %}</h2>
        <div class="btn-toolbar mb-2 mb-md-0">
            <a class="btn btn btn-sm btn-outline-primary" role="button" href="{{ url_for('leads.new_lead') }}">
                <span data-feather="plus"></span>
                  New
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-4">
            <div class="reports-heading"><span data-feather="dollar-sign"></span> Deal (Sales) Reports</div>
            <ul class="list-group">
                <li class="list-group-item">
                    <a href="{{ url_for('reports.deal_stages') }}">Net revenue report by deal stages</a>
                </li>
                <li class="list-group-item">
                    <a href="{{ url_for('reports.deals_closed') }}">Deal stage revenue report (Account wise)</a>
                </li>
                {% if current_user.role.name == 'admin' %}
                    <li class="list-group-item">
                        <a href="{{ url_for('reports.deal_stage_by_users') }}">Deal stage revenue report (User wise)</a>
                    </li>
                {% endif %}
                <li class="list-group-item">
                    <a href="#">Deals closed (sales) by Time</a>
                </li>
                <li class="list-group-item">
                    <a href="#">Sales forecast</a>
                </li>
            </ul>
        </div>
        <div class="col-4">
            <div class="reports-heading"><span data-feather="users"></span> Customer (Accounts) Reports</div>
            <ul class="list-group">
                <li class="list-group-item">
                    <a href="{{ url_for('reports.deal_stages') }}">Account report by User</a>
                </li>
                <li class="list-group-item">
                    <a href="{{ url_for('reports.deals_closed') }}">Deal stage reports by Account</a>
                </li>
            </ul>
        </div>
    </div>
    {% endblock %}