crm/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager

from .config import Config

# database handle
db = SQLAlchemy(session_options={"autoflush": False})

# encryptor handle
bcrypt = Bcrypt()

# manage user login
login_manager = LoginManager()

# function name of the login route that
# tells the path which facilitates authentication
login_manager.login_view = 'users.login'


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    app.url_map.strict_slashes = False
    app.jinja_env.globals.update(zip=zip)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)

    # include the routes
    # from crm import routes
    from crm.main.routes import main
    from crm.users.routes import users
    from crm.leads.routes import leads
    from crm.accounts.routes import accounts
    from crm.contacts.routes import contacts
    from crm.deals.routes import deals
    from crm.settings.routes import settings
    from crm.reports.routes import reports

    # register routes with blueprint
    app.register_blueprint(main)
    app.register_blueprint(users)
    app.register_blueprint(settings)
    app.register_blueprint(leads)
    app.register_blueprint(accounts)
    app.register_blueprint(contacts)
    app.register_blueprint(deals)
    app.register_blueprint(reports)

    return app

crm/contacts/routes.py
from flask_login import current_user, login_required
from flask import render_template, flash, url_for, redirect, request, Blueprint, session
import json
from sqlalchemy import or_, text
from datetime import date, timedelta

from crm import db
from .models import Contact
from crm.common.paginate import Paginate
from crm.common.filters import CommonFilters
from .forms import NewContact, FilterContacts, filter_contacts_adv_filters_query
from crm.users.utils import upload_avatar

from crm.rbac import check_access

contacts = Blueprint('contacts', __name__)


def set_filters(f_id, module):
    today = date.today()
    filter_d = True
    if f_id == 1:
        filter_d = text("Date(%s.date_created)='%s'" % (module, today))
    elif f_id == 2:
        filter_d = text("Date(%s.date_created)='%s'" % (module, (today - timedelta(1))))
    elif f_id == 3:
        filter_d = text("Date(%s.date_created) > current_date - interval '7' day" % module)
    elif f_id == 4:
        filter_d = text("Date(%s.date_created) > current_date - interval '30' day" % module)
    return filter_d


def set_date_filters(filters, module, key):
    filter_d = True
    if request.method == 'POST':
        if filters.advanced_user.data:
            filter_d = set_filters(filters.advanced_user.data['id'], module)
            session[key] = filters.advanced_user.data['id']
        else:
            session.pop(key, None)
    else:
        if key in session:
            filter_d = set_filters(session[key], module)
            filters.advanced_user.data = filter_contacts_adv_filters_query()[session[key] - 1]
    return filter_d


def reset_contacts_filters():
    if 'contacts_owner' in session:
        session.pop('contacts_owner', None)
    if 'contacts_search' in session:
        session.pop('contacts_search', None)
    if 'contacts_acc_owner' in session:
        session.pop('contacts_acc_owner', None)
    if 'contacts_date_created' in session:
        session.pop('contacts_date_created', None)


@contacts.route("/contacts", methods=['GET', 'POST'])
@login_required
@check_access('contacts', 'view')
def get_contacts_view():
    filters = FilterContacts()
    search = CommonFilters.set_search(filters, 'contacts_search')
    owner = CommonFilters.set_owner(filters, 'Contact', 'contacts_owner')
    account = CommonFilters.set_accounts(filters, 'Contact', 'contacts_acc_owner')
    advanced_filters = set_date_filters(filters, 'Contact', 'contacts_date_created')

    query = Contact.query.filter(or_(
            Contact.first_name.ilike(f'%{search}%'),
            Contact.last_name.ilike(f'%{search}%'),
            Contact.email.ilike(f'%{search}%'),
            Contact.phone.ilike(f'%{search}%'),
            Contact.mobile.ilike(f'%{search}%'),
            Contact.address_line.ilike(f'%{search}%'),
            Contact.addr_state.ilike(f'%{search}%'),
            Contact.addr_city.ilike(f'%{search}%'),
            Contact.post_code.ilike(f'%{search}%')
        ) if search else True)\
        .filter(account) \
        .filter(owner) \
        .filter(advanced_filters) \
        .order_by(Contact.date_created.desc())

    return render_template("contacts/contacts_list.html", title="Contacts View",
                           contacts=Paginate(query=query), filters=filters)


@contacts.route("/contacts/acc/<int:account_id>")
@login_required
@check_access('contacts', 'view')
def get_account_contacts(account_id):
    items = Contact.query\
        .filter_by(account_id=account_id)\
        .order_by(Contact.date_created.desc())\
        .all()

    d = []
    for item in items:
        f = {'id': item.id, 'name': item.get_contact_name()}
        d.append(f)
    return json.dumps(d)


@contacts.route("/contacts/new", methods=['GET', 'POST'])
@login_required
@check_access('contacts', 'create')
def new_contact():
    form = NewContact()
    if request.method == 'POST':
        if form.validate_on_submit():
            contact = Contact(first_name=form.first_name.data,
                              last_name=form.last_name.data,
                              email=form.email.data,
                              phone=form.phone.data,
                              mobile=form.mobile.data,
                              address_line=form.address_line.data,
                              addr_state=form.addr_state.data,
                              addr_city=form.addr_city.data,
                              post_code=form.post_code.data,
                              country=form.country.data,
                              notes=form.notes.data)

            contact.account = form.accounts.data

            if form.avatar.data:
                picture_file = upload_avatar(contact, form.avatar.data)
                contact.avatar = picture_file

            if current_user.role.name == 'admin':
                contact.contact_owner = form.assignees.data
            else:
                contact.contact_owner = current_user

            db.session.add(contact)
            db.session.commit()
            flash('Contact has been successfully created!', 'success')
            return redirect(url_for('contacts.get_contacts_view'))
        else:
            print(form.errors)

            flash('Your form has errors! Please check the fields', 'danger')
    return render_template("contacts/new_contact.html", title="New Contact", form=form)


@contacts.route("/contacts/<int:contact_id>")
@login_required
@check_access('contacts', 'view')
def get_contact_view(contact_id):
    contact = Contact.query.filter_by(id=contact_id).first()
    return render_template("contacts/contact_view.html", title="View Contact", contact=contact)


@contacts.route("/contacts/del/<int:contact_id>")
@login_required
@check_access('contacts', 'delete')
def delete_contact(contact_id):
    Contact.query.filter_by(id=contact_id).delete()
    db.session.commit()
    flash('Contact removed successfully!', 'success')
    return redirect(url_for('contacts.get_contacts_view'))


@contacts.route("/contacts/reset_filters")
@login_required
@check_access('contacts', 'view')
def reset_filters():
    reset_contacts_filters()
    return redirect(url_for('contacts.get_contacts_view'))

crm/settings/routes.py
from flask import Blueprint
from flask_login import current_user, login_required
from flask import render_template, flash, url_for, redirect, request
from sqlalchemy.exc import IntegrityError

from crm.users.forms import UpdateProfile, UpdateRoleForm, NewRoleForm, UpdateUser, ResourceForm
from crm.users.utils import upload_avatar
from crm.users.models import User, Role, Resource

from crm import db, bcrypt
from crm.rbac import check_access, is_admin

settings = Blueprint('settings', __name__)


@settings.route("/settings/profile", methods=['GET', 'POST'])
@login_required
def settings_profile():
    form = UpdateProfile()
    if request.method == 'POST':
        if form.validate_on_submit():
            if form.picture.data:
                picture_file = upload_avatar(current_user, form.picture.data)
                current_user.avatar = picture_file
            current_user.first_name = form.first_name.data
            current_user.last_name = form.last_name.data
            current_user.email = form.email.data
            db.session.commit()
            flash('Your account information has been successfully updated', 'success')
            return redirect(url_for('settings.settings_profile'))
    elif request.method == 'GET':
        form.first_name.data = current_user.first_name
        form.last_name.data = current_user.last_name
        form.email.data = current_user.email
    return render_template("settings/profile.html", title="My Profile", form=form)


# get all users except the current one (admin)
@settings.route("/settings/staff")
@login_required
@check_access("staff", "view")
def settings_staff_list():
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 10, type=int)
    users = User.query\
        .filter(User.id != current_user.id)\
        .order_by(User.id.asc())\
        .paginate(per_page=per_page, page=page)
    return render_template("settings/staff_list.html", title="User Management", users=users)


@settings.route("/settings/staff/<int:user_id>")
@login_required
@check_access("staff", "view")
def settings_staff_view(user_id):
    user = User.query.filter(User.id == user_id).first()
    return render_template("settings/staff_view.html", title="View Staff", user=user)


@settings.route("/settings/staff/edit/<int:user_id>", methods=['GET', 'POST'])
@login_required
@check_access("staff", "update")
def settings_staff_update(user_id):
    form = UpdateUser()
    user = User.query.filter(User.id == user_id).first()

    acl = Role.query\
        .with_entities(Role.id,
                       Resource.id,
                       Resource.name,
                       Resource.can_view,
                       Resource.can_create,
                       Resource.can_edit,
                       Resource.can_delete)\
        .filter_by(id=user.role_id)\
        .join(Role.resources)\
        .order_by(Resource.id.asc())\
        .all()

    if request.method == 'POST':
        if form.validate_on_submit():
            if form.picture.data:
                picture_file = upload_avatar(user, form.picture.data)
                user.avatar = picture_file
            user.first_name = form.first_name.data
            user.last_name = form.last_name.data
            user.email = form.email.data
            user.role = form.role.data
            user.is_user_active = form.is_user_active.data
            user.is_first_login = form.is_first_login.data

            for permission in form.permissions:
                resource = Resource.query.filter_by(id=permission.resource_id.data).first()
                resource.can_view = permission.can_view.data
                resource.can_create = permission.can_create.data
                resource.can_edit = permission.can_edit.data
                resource.can_delete = permission.can_delete.data

            try:
                db.session.commit()
                flash('Staff member information has been successfully updated', 'success')
                return redirect(url_for('settings.settings_staff_view', user_id=user.id))
            except IntegrityError:
                db.session.rollback()
                form.email.errors = [f'Email \'{form.email.data}\' already exists!']
                flash('User update failed! Form has errors', 'danger')

        else:
            print(form.errors)
            flash('User update failed! Form has errors', 'danger')
    elif request.method == 'GET':
        form.first_name.data = user.first_name
        form.last_name.data = user.last_name
        form.email.data = user.email
        if user.avatar:
            form.picture.data = user.avatar
        form.role.data = user.role
        form.is_user_active.data = user.is_user_active
        form.is_first_login.data = user.is_first_login

        for l in acl:
            resource_form = ResourceForm()
            resource_form.resource_id = l.id
            resource_form.name = l.name
            resource_form.can_view = l.can_view
            resource_form.can_create = l.can_create
            resource_form.can_edit = l.can_edit
            resource_form.can_delete = l.can_delete
            form.permissions.append_entry(resource_form)

    return render_template("settings/staff_update.html", title="Update Staff", form=form)


@settings.route("/settings/staff/new", methods=['GET', 'POST'])
@login_required
@check_access("staff", "create")
def settings_staff_new():
    form = UpdateUser()
    if request.method == 'POST':
        hashed_pwd = bcrypt.generate_password_hash('123').decode('utf-8')
        if form.validate_on_submit():
            user = User()
            user.first_name = form.first_name.data
            user.last_name = form.last_name.data
            user.email = form.email.data
            user.password = hashed_pwd
            if form.picture.data:
                picture_file = upload_avatar(user, form.picture.data)
                user.avatar = picture_file
            user.role = form.role.data
            user.is_user_active = form.is_user_active.data
            user.is_first_login = form.is_first_login.data

            db.session.add(user)
            db.session.commit()
            flash('User has been successfully created!', 'success')
            return redirect(url_for('settings.settings_staff_list'))
        else:
            print(form.errors)
            flash(f'Failed to register user!', 'danger')
    return render_template("settings/new_user.html", title="New Staff Member", form=form)


@settings.route("/settings/staff/del/<int:user_id>")
@login_required
@check_access("staff", "remove")
def settings_staff_remove(user_id):
    User.query.filter(User.id == user_id).delete()
    db.session.commit()
    return redirect(url_for('main.home'))


@settings.route("/settings/staff/del/<email>", methods=['DELETE'])
@login_required
@check_access("staff", "remove")
def settings_staff_remove_by_email(email):
    User.query.filter(User.email == email).delete()
    db.session.commit()
    flash('User removed successfully!', 'success')
    return redirect(url_for('main.home'))


@settings.route("/settings/email", methods=['GET', 'POST'])
@login_required
def email_settings():
    flash('Email settings saved', 'success')
    return redirect(url_for('main.home'))


@settings.route("/settings/roles")
@login_required
@is_admin
def settings_roles_view():
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 10, type=int)
    roles = Role.query\
        .filter(Role.name != 'admin')\
        .order_by(Role.id.asc())\
        .paginate(per_page=per_page, page=page)
    return render_template("settings/roles_list.html", title="Roles & Permissions", roles=roles)


@settings.route("/settings/role/new", methods=['GET', 'POST'])
@login_required
@is_admin
def settings_roles_new():
    form = NewRoleForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            role = Role()
            role.name = form.name.data

            for permission in form.permissions:
                resource = Resource()
                resource.name = permission.form.name.data
                resource.can_view = permission.form.can_view.data
                resource.can_create = permission.form.can_create.data
                resource.can_edit = permission.form.can_edit.data
                resource.can_delete = permission.form.can_delete.data
                role.resources.append(resource)

            db.session.add(role)
            db.session.commit()

            flash('Role has been successfully created!', 'success')
            return redirect(url_for('settings.settings_roles_view'))
        else:
            flash('Failed to create new role!', 'danger')
    elif request.method == 'GET':
        resources = [
            ResourceForm(name='staff', can_view=False,
                         can_create=False, can_edit=False, can_delete=False),
            ResourceForm(name='leads', can_view=True,
                         can_create=True, can_edit=True, can_delete=True)
        ]

        for resource in resources:
            form.permissions.append_entry(resource.data)
    return render_template("settings/role_new.html", title="Create New Role", form=form)


@settings.route("/settings/role/edit/<role_id>", methods=['GET', 'POST'])
@login_required
@is_admin
def settings_roles_update(role_id):
    role = Role.query.filter_by(id=role_id).first()
    form = UpdateRoleForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            role.name = form.name.data.lower()
            role.set_permissions(form.permissions)

            try:
                db.session.commit()
                flash('Role successfully created!', 'success')
                return redirect(url_for('settings.settings_roles_view'))
            except IntegrityError:
                db.session.rollback()
                if form.name.data == 'admin':

crm/templates/settings/roles_list.html
{% extends './layout.html' %}
{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2 class="h4">{% if title %}{{title}}{% else %}No Title{% endif %}</h2>
        <div class="btn-toolbar mb-2 mb-md-0">
            <a class="btn btn btn-sm btn-outline-primary" role="button" href="{{ url_for('settings.settings_roles_new') }}">
                <span data-feather="plus"></span>
                      Add New Role
            </a>
        </div>
    </div>
    {% if roles.items|length > 0 %}
    <div class="table-responsive">
        <table class="table table-hover">
            <thead class="thead-light">
            <tr>
                <th scope="col">#</th>
                <th></th>
                <th scope="col">Role Name</th>
            </tr>
            </thead>
            <tbody>
            {% for role in roles.items %}
                <tr>
                    <td scope="row">{{ role.id }}</td>
                    <td>
                        <a href="{{ url_for('settings.settings_roles_update', role_id=role.id) }}"
                           class="btn btn-outline-secondary btn-sm mr-3" role="button">
                            <span data-feather="edit"></span>
                        </a>
                        <a href="#" data-target="#deleteNotificationModal_{{ role.id }}"
                           class="btn btn-outline-secondary btn-sm mr-3" data-toggle="modal" role="button">
                            <span data-feather="trash"></span>
                        </a>
                        <a href="#"
                           class="btn btn-outline-secondary btn-sm mr-3" role="button">
                            <span data-feather="arrow-up-right"></span>
                        </a>

                        <!-- Delete Warning Modal -->
                            <div class="modal fade" id="deleteNotificationModal_{{ role.id }}"
                                 tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel_{{ role.id }}" aria-hidden="true">
                              <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                  <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel_{{ role.id }}">Delete Role `{{ role.name }}`?</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                      <span aria-hidden="true">&times;</span>
                                    </button>
                                  </div>
                                  <div class="modal-body text-center">
                                      <div>
                                          <strong>Are you sure you want delete this role?</strong>
                                      </div>
                                      <div>Please note that once deleted the role entry will be permanently deleted</div>
                                  </div>
                                  <div class="modal-footer">
                                    <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button>
                                    <button type="button" id="del_{{ role.id }}" class="btn btn-outline-primary">Delete Role</button>
                                    <script>
                                        $(document).ready(function() {
                                            $("#del_{{ role.id }}").on("click", function(e) {
                                                window.location="{{ url_for('settings.settings_roles_remove', role_id=role.id) }}"
                                            });
                                        });
                                    </script>
                                  </div>
                                </div>
                              </div>
                            </div>
                        </td>
                    <td scope="row">{{ role.name }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
        <!-- pagination -->
        {% if roles.total > 10 %}
            {% with view_id="settings.settings_roles_view", items=roles %}
                {% include "common/pagination.html" %}
            {% endwith %}
        {% endif %}
    {% else %}
        <div class="container text-center pt-4">
            <div><span data-feather="eye-off"></span></div>
            <p>You have not added any role as yet ...</p>
        </div>
    {% endif %}
{% endblock %}

crm/templates/settings/staff_list.html
{% extends './layout.html' %}
{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2 class="h4">{% if title %}{{title}}{% else %}No Title{% endif %}</h2>
        <div class="btn-toolbar mb-2 mb-md-0">
            <a class="btn btn btn-sm btn-outline-primary" role="button" href="{{ url_for('settings.settings_staff_new') }}">
                <span data-feather="plus"></span>
                      Add New User
            </a>
        </div>
    </div>
    {% if users.items|length > 0 %}
    <div class="table-responsive">
        <table class="table table-hover">
            <thead class="thead-light">
            <tr>
                <th scope="col">#</th>
                <th></th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Is Active</th>
            </tr>
            </thead>
            <tbody>
            {% for user in users.items %}
                <tr>
                    <td scope="row">{{ user.id }}</td>
                    <td>
                        <a href="{{ url_for('settings.settings_staff_update', user_id=user.id) }}"
                           class="btn btn-outline-secondary btn-sm mr-3" role="button">
                            <span data-feather="edit"></span>
                        </a>
                        <a href="#" data-target="#deleteNotificationModal_{{ user.id }}"
                           class="btn btn-outline-secondary btn-sm mr-3" data-toggle="modal" role="button">
                            <span data-feather="trash"></span>
                        </a>
                        <a href="{{ url_for('settings.settings_staff_view', user_id=user.id) }}"
                           class="btn btn-outline-secondary btn-sm mr-3" role="button">
                            <span data-feather="arrow-up-right"></span>
                        </a>

                        <!-- Delete Warning Modal -->
                            <div class="modal fade" id="deleteNotificationModal_{{ user.id }}"
                                 tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel_{{ user.id }}" aria-hidden="true">
                              <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                  <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel_{{ user.id }}">Delete User?</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                      <span aria-hidden="true">&times;</span>
                                    </button>
                                  </div>
                                  <div class="modal-body text-center">
                                      <div class="user_profile_pic">
                                          {% include "common/user_profile_pic.html" %}
                                          <h4>{{ user.first_name }} {{ user.last_name }}</h4>
                                      </div>
                                      <div>
                                          <strong>Are you sure you want delete this user?</strong>
                                      </div>
                                      <div>Please note that once deleted the user cannot be recovered</div>
                                  </div>
                                  <div class="modal-footer">
                                    <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button>
                                    <button type="button" class="btn btn-outline-primary">Delete User</button>
                                  </div>
                                </div>
                              </div>
                            </div>

                    </td>
                    <td>{% with owner=user %}{% include 'common/owner_cell.html' %}{% endwith %}</td>
                    <td><span data-feather="mail" class="mr-1"></span> {{ user.email }}</td>
                    <td>{{ 'Yes' if user.is_user_active==True else 'No' }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
        <!-- pagination -->
        {% if users.total > 10 %}
            {% with view_id="settings.settings_staff_list", items=users %}
                {% include "common/pagination.html" %}
            {% endwith %}
        {% endif %}
    {% else %}
        <div class="container text-center pt-4">
            <div><span data-feather="eye-off"></span></div>
            <p>You have not added any staff member as yet ...</p>
        </div>
    {% endif %}
{% endblock %}

crm/templates/settings/staff_view.html
{% extends './layout.html' %}
{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2 class="h4">{% if title %}{{title}}{% else %}No Title{% endif %}</h2>
        <div class="btn-toolbar mb-2 mb-md-0">
            <a class="btn btn btn-sm btn-outline-primary mr-2" role="button" href="{{ url_for('settings.settings_staff_new') }}">
                <span data-feather="edit"></span>
                      Edit User
            </a>
            <a class="btn btn btn-sm btn-outline-secondary" role="button" href="{{ url_for('settings.settings_staff_list') }}">
                <span data-feather="arrow-left"></span>
                      Back to List
            </a>
        </div>
    </div>
    <div class="content-section mb-4">
        <div class="media">
            {% if user.avatar %}
                <img class="rounded-circle account-img"
                 src="{{ url_for('static', filename='profile_imgs/' + user.avatar) }}"
                 width="128" height="128" />
            {% else %}
                <img class="rounded-circle account-img"
                 src="{{ url_for('static', filename='imgs/default_avatar.png') }}"
                 width="128" height="128" />
            {% endif %}
            <div class="media-body ml-3 mt-3">
                <h2 class="account-heading">{{ user.first_name + ' ' + user.last_name }}</h2>
                <p class="text-secondary"><span data-feather="mail"></span> {{ user.email }}</p>
            </div>
        </div>
    </div>
{% endblock %}