crm/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager

from .config import Config

# database handle
db = SQLAlchemy(session_options={"autoflush": False})

# encryptor handle
bcrypt = Bcrypt()

# manage user login
login_manager = LoginManager()

# function name of the login route that
# tells the path which facilitates authentication
login_manager.login_view = 'users.login'


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    app.url_map.strict_slashes = False
    app.jinja_env.globals.update(zip=zip)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)

    # include the routes
    # from crm import routes
    from crm.main.routes import main
    from crm.users.routes import users
    from crm.leads.routes import leads
    from crm.accounts.routes import accounts
    from crm.contacts.routes import contacts
    from crm.deals.routes import deals
    from crm.settings.routes import settings
    from crm.reports.routes import reports

    # register routes with blueprint
    app.register_blueprint(main)
    app.register_blueprint(users)
    app.register_blueprint(settings)
    app.register_blueprint(leads)
    app.register_blueprint(accounts)
    app.register_blueprint(contacts)
    app.register_blueprint(deals)
    app.register_blueprint(reports)

    return app

crm/contacts/routes.py
from flask_login import current_user, login_required
from flask import render_template, flash, url_for, redirect, request, Blueprint, session
import json
from sqlalchemy import or_, text
from datetime import date, timedelta

from crm import db
from .models import Contact
from crm.common.paginate import Paginate
from crm.common.filters import CommonFilters
from .forms import NewContact, FilterContacts, filter_contacts_adv_filters_query
from crm.users.utils import upload_avatar

from crm.rbac import check_access

contacts = Blueprint('contacts', __name__)


def set_filters(f_id, module):
    today = date.today()
    filter_d = True
    if f_id == 1:
        filter_d = text("Date(%s.date_created)='%s'" % (module, today))
    elif f_id == 2:
        filter_d = text("Date(%s.date_created)='%s'" % (module, (today - timedelta(1))))
    elif f_id == 3:
        filter_d = text("Date(%s.date_created) > current_date - interval '7' day" % module)
    elif f_id == 4:
        filter_d = text("Date(%s.date_created) > current_date - interval '30' day" % module)
    return filter_d


def set_date_filters(filters, module, key):
    filter_d = True
    if request.method == 'POST':
        if filters.advanced_user.data:
            filter_d = set_filters(filters.advanced_user.data['id'], module)
            session[key] = filters.advanced_user.data['id']
        else:
            session.pop(key, None)
    else:
        if key in session:
            filter_d = set_filters(session[key], module)
            filters.advanced_user.data = filter_contacts_adv_filters_query()[session[key] - 1]
    return filter_d


def reset_contacts_filters():
    if 'contacts_owner' in session:
        session.pop('contacts_owner', None)
    if 'contacts_search' in session:
        session.pop('contacts_search', None)
    if 'contacts_acc_owner' in session:
        session.pop('contacts_acc_owner', None)
    if 'contacts_date_created' in session:
        session.pop('contacts_date_created', None)


@contacts.route("/contacts", methods=['GET', 'POST'])
@login_required
@check_access('contacts', 'view')
def get_contacts_view():
    filters = FilterContacts()
    search = CommonFilters.set_search(filters, 'contacts_search')
    owner = CommonFilters.set_owner(filters, 'Contact', 'contacts_owner')
    account = CommonFilters.set_accounts(filters, 'Contact', 'contacts_acc_owner')
    advanced_filters = set_date_filters(filters, 'Contact', 'contacts_date_created')

    query = Contact.query.filter(or_(
            Contact.first_name.ilike(f'%{search}%'),
            Contact.last_name.ilike(f'%{search}%'),
            Contact.email.ilike(f'%{search}%'),
            Contact.phone.ilike(f'%{search}%'),
            Contact.mobile.ilike(f'%{search}%'),
            Contact.address_line.ilike(f'%{search}%'),
            Contact.addr_state.ilike(f'%{search}%'),
            Contact.addr_city.ilike(f'%{search}%'),
            Contact.post_code.ilike(f'%{search}%')
        ) if search else True)\
        .filter(account) \
        .filter(owner) \
        .filter(advanced_filters) \
        .order_by(Contact.date_created.desc())

    return render_template("contacts/contacts_list.html", title="Contacts View",
                           contacts=Paginate(query=query), filters=filters)


@contacts.route("/contacts/acc/<int:account_id>")
@login_required
@check_access('contacts', 'view')
def get_account_contacts(account_id):
    items = Contact.query\
        .filter_by(account_id=account_id)\
        .order_by(Contact.date_created.desc())\
        .all()

    d = []
    for item in items:
        f = {'id': item.id, 'name': item.get_contact_name()}
        d.append(f)
    return json.dumps(d)


@contacts.route("/contacts/new", methods=['GET', 'POST'])
@login_required
@check_access('contacts', 'create')
def new_contact():
    form = NewContact()
    if request.method == 'POST':
        if form.validate_on_submit():
            contact = Contact(first_name=form.first_name.data,
                              last_name=form.last_name.data,
                              email=form.email.data,
                              phone=form.phone.data,
                              mobile=form.mobile.data,
                              address_line=form.address_line.data,
                              addr_state=form.addr_state.data,
                              addr_city=form.addr_city.data,
                              post_code=form.post_code.data,
                              country=form.country.data,
                              notes=form.notes.data)

            contact.account = form.accounts.data

            if form.avatar.data:
                picture_file = upload_avatar(contact, form.avatar.data)
                contact.avatar = picture_file

            if current_user.role.name == 'admin':
                contact.contact_owner = form.assignees.data
            else:
                contact.contact_owner = current_user

            db.session.add(contact)
            db.session.commit()
            flash('Contact has been successfully created!', 'success')
            return redirect(url_for('contacts.get_contacts_view'))
        else:
            print(form.errors)

            flash('Your form has errors! Please check the fields', 'danger')
    return render_template("contacts/new_contact.html", title="New Contact", form=form)


@contacts.route("/contacts/<int:contact_id>")
@login_required
@check_access('contacts', 'view')
def get_contact_view(contact_id):
    contact = Contact.query.filter_by(id=contact_id).first()
    return render_template("contacts/contact_view.html", title="View Contact", contact=contact)


@contacts.route("/contacts/del/<int:contact_id>")
@login_required
@check_access('contacts', 'delete')
def delete_contact(contact_id):
    Contact.query.filter_by(id=contact_id).delete()
    db.session.commit()
    flash('Contact removed successfully!', 'success')
    return redirect(url_for('contacts.get_contacts_view'))


@contacts.route("/contacts/reset_filters")
@login_required
@check_access('contacts', 'view')
def reset_filters():
    reset_contacts_filters()
    return redirect(url_for('contacts.get_contacts_view'))

crm/leads/routes.py
import pandas as pd
from sqlalchemy import or_
from wtforms import Label

from flask import Blueprint, session, Response
from flask_login import current_user, login_required
from flask import render_template, flash, url_for, redirect, request

from crm import db
from .models import Lead
from crm.common.paginate import Paginate
from crm.common.filters import CommonFilters
from .filters import set_date_filters, set_source, set_status
from .forms import NewLead, ImportLeads, ConvertLead, \
    FilterLeads, BulkOwnerAssign, BulkLeadSourceAssign, BulkLeadStatusAssign, BulkDelete

from crm.rbac import check_access, is_admin

leads = Blueprint('leads', __name__)


def reset_lead_filters():
    if 'lead_owner' in session:
        session.pop('lead_owner', None)
    if 'lead_search' in session:
        session.pop('lead_search', None)
    if 'lead_date_created' in session:
        session.pop('lead_date_created', None)
    if 'lead_source' in session:
        session.pop('lead_source', None)
    if 'lead_status' in session:
        session.pop('lead_status', None)


@leads.route("/leads", methods=['GET', 'POST'])
@login_required
@check_access('leads', 'view')
def get_leads_view():
    filters = FilterLeads()
    search = CommonFilters.set_search(filters, 'lead_search')
    owner = CommonFilters.set_owner(filters, 'Lead', 'lead_owner')
    advanced_filters = set_date_filters(filters, 'lead_date_created')
    source_filter = set_source(filters, 'lead_source')
    status_filter = set_status(filters, 'lead_status')

    query = Lead.query \
        .filter(or_(
            Lead.title.ilike(f'%{search}'),
            Lead.first_name.ilike(f'%{search}'),
            Lead.last_name.ilike(f'%{search}'),
            Lead.email.ilike(f'%{search}'),
            Lead.company_name.ilike(f'%{search}'),
            Lead.phone.ilike(f'%{search}'),
            Lead.mobile.ilike(f'%{search}'),
        ) if search else True) \
        .filter(source_filter) \
        .filter(status_filter) \
        .filter(owner) \
        .filter(advanced_filters) \
        .order_by(Lead.date_created.desc())

    bulk_form = {
        'owner': BulkOwnerAssign(),
        'lead_source': BulkLeadSourceAssign(),
        'lead_status': BulkLeadStatusAssign(),
        'delete': BulkDelete()
    }

    return render_template("leads/leads_list.html", title="Leads View",
                           leads=Paginate(query), filters=filters, bulk_form=bulk_form)


@leads.route("/leads/new", methods=['GET', 'POST'])
@login_required
@check_access('leads', 'create')
def new_lead():
    form = NewLead()
    if request.method == 'POST':
        if form.validate_on_submit():
            lead = Lead(title=form.title.data,
                        first_name=form.first_name.data, last_name=form.last_name.data,
                        email=form.email.data, company_name=form.company.data,
                        address_line=form.address_line.data, addr_state=form.addr_state.data,
                        addr_city=form.addr_city.data, post_code=form.post_code.data,
                        country=form.country.data, source=form.lead_source.data,
                        status=form.lead_status.data, notes=form.notes.data)

            if current_user.role.name == 'admin':
                lead.owner = form.assignees.data
            else:
                lead.owner = current_user

            db.session.add(lead)
            db.session.commit()
            flash('New lead has been successfully created!', 'success')
            return redirect(url_for('leads.get_leads_view'))
        else:
            for error in form.errors:
                print(error)
            flash('Your form has errors! Please check the fields', 'danger')
    return render_template("leads/new_lead.html", title="New Lead", form=form)


@leads.route("/leads/edit/<int:lead_id>", methods=['GET', 'POST'])
@login_required
@check_access('leads', 'update')
def update_lead(lead_id):
    lead = Lead.get_by_id(lead_id)
    if not lead:
        return redirect(url_for('leads.get_leads_view'))

    form = NewLead()
    if request.method == 'POST':
        if form.validate_on_submit():
            lead.title = form.title.data
            lead.first_name = form.first_name.data
            lead.last_name = form.last_name.data
            lead.email = form.email.data
            lead.company_name = form.company.data
            lead.phone = form.phone.data
            lead.mobile = form.mobile.data
            lead.address_line = form.address_line.data
            lead.addr_state = form.addr_state.data
            lead.addr_city = form.addr_city.data
            lead.post_code = form.post_code.data
            lead.country = form.country.data
            lead.owner = form.assignees.data
            lead.source = form.lead_source.data
            lead.status = form.lead_status.data
            lead.notes = form.notes.data
            db.session.commit()
            flash('The lead has been successfully updated', 'success')
            return redirect(url_for('leads.get_lead_view', lead_id=lead.id))
        else:
            print(form.errors)
            flash('User update failed! Form has errors', 'danger')
    elif request.method == 'GET':
        form.title.data = lead.title
        form.first_name.data = lead.first_name
        form.last_name.data = lead.last_name
        form.email.data = lead.email
        form.company.data = lead.company_name
        form.phone.data = lead.phone
        form.mobile.data = lead.mobile
        form.address_line.data = lead.address_line
        form.addr_state.data = lead.addr_state
        form.addr_city.data = lead.addr_city
        form.post_code.data = lead.post_code
        form.country.data = lead.country
        form.assignees.data = lead.owner
        form.lead_source.data = lead.source
        form.lead_status.data = lead.status
        form.notes.data = lead.notes
        form.submit.label = Label('update_lead', 'Update Lead')
    return render_template("leads/new_lead.html", title="Update Lead", form=form)


@leads.route("/leads/<int:lead_id>")
@login_required
@check_access('leads', 'view')
def get_lead_view(lead_id):
    lead = Lead.query.filter_by(id=lead_id).first()
    return render_template("leads/lead_view.html", title="View Lead", lead=lead)


@leads.route("/leads/convert/<int:lead_id>", methods=['GET', 'POST'])
@login_required
@check_access('leads', 'view')
@check_access('accounts', 'create')
@check_access('contacts', 'create')
@check_access('deals', 'create')
def convert_lead(lead_id):
    lead = Lead.query.filter_by(id=lead_id).first()
    form = ConvertLead()
    form.account_name.data = lead.company_name
    form.account_email.data = lead.email

    if request.method == 'POST':
        if form.validate_on_submit():
            if form.use_account_information.data and form.use_contact_information.data:
                # create both account and contact

                pass
            elif form.use_account_information.data and not form.use_contact_information.data:
                # create account only (and contact if chosen from dropdown)
                if not form.account_name.data:
                    form.account_name.errors = ['Please enter account name']
                if not form.account_name.data:
                    form.account_email.errors = ['Please enter account email']
            elif not form.use_account_information.data and form.use_contact_information.data:
                pass
                # create contact only (account dropdown must be selected)
            elif not form.use_account_information.data and not form.use_contact_information.data:
                # account must be selected in dropdown (and create contact if selected in dropdown)
                if not form.accounts.data:
                    form.accounts.errors = ['Please select an account']
                pass

            flash('Leads has been successfully converted!', 'success')
        else:
            flash('Your form has errors! Please check the fields', 'danger')
    else:
        form.title.data = lead.title
    return render_template("leads/lead_convert.html", title="Convert Lead", lead=lead, form=form)


@leads.route("/leads/import", methods=['GET', 'POST'])
@login_required
@is_admin
def import_bulk_leads():
    form = ImportLeads()
    if request.method == 'POST':
        ind = 0
        if form.validate_on_submit():
            data = pd.read_csv(form.csv_file.data)

            for _, row in data.iterrows():
                lead = Lead(first_name=row['first_name'], last_name=row['last_name'],
                            email=row['email'], company_name=row['company_name'])
                lead.owner = current_user
                if form.lead_source.data:
                    lead.source = form.lead_source.data
                db.session.add(lead)
                ind = ind + 1

            db.session.commit()
            flash(f'{ind} new lead(s) has been successfully imported!', 'success')
        else:
            flash('Your form has errors! Please check the fields', 'danger')
    return render_template("leads/leads_import.html", title="Import Leads", form=form)


@leads.route("/leads/reset_filters")
@login_required
@check_access('leads', 'view')
def reset_filters():
    reset_lead_filters()
    return redirect(url_for('leads.get_leads_view'))


@leads.route("/leads/bulk_owner_assign", methods=['POST'])
@login_required
@is_admin
def bulk_owner_assign():
    form = BulkOwnerAssign()
    if request.method == 'POST':
        if form.validate_on_submit():
            if form.owners_list.data:
                ids = [int(x) for x in request.form['leads_owner'].split(',')]
                Lead.query\
                    .filter(Lead.id.in_(ids))\
                    .update({
                        Lead.owner_id: form.owners_list.data.id
                    }, synchronize_session=False)
                db.session.commit()

crm/templates/leads/bulk_lead_delete_modal.html
<div class="modal fade ba_modal" id="leadsDeleteModal" tabindex="-1" role="dialog"
     aria-labelledby="leadsDeleteModalLabel"
     aria-hidden="true">
    <form class="bulk-assign-lead-form" method="POST" action="{{ url_for('leads.bulk_delete') }}">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="leadsDeleteModalLabel">Delete Leads</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="alert alert-warning" role="alert">
                  <h5 class="alert-heading">Are you sure?</h5>
                    <p>Please note that once deleted the records cannot be recovered</p>
                </div>
                {{ bulk_form.delete.hidden_tag() }} <!-- security 'csrf' token -->
                <input type="hidden" class="leads_data" name="leads_to_delete">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                {{ bulk_form.delete.submit(id="bulk-lead-submit", class="btn btn-primary") }}
            </div>
        </div>
    </div>
     </form>
</div>

crm/templates/leads/bulk_owner_assign_modal.html
<div class="modal fade ba_modal" id="leadOwnerAssignModal" tabindex="-1" role="dialog"
     aria-labelledby="leadOwnerAssignModalLabel"
     aria-hidden="true">
    <form class="bulk-assign-lead-form" method="POST" action="{{ url_for('leads.bulk_owner_assign') }}">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="leadOwnerAssignModalLabel">Bulk Owner Assign ...</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="modal-notif-area"></div>
                    {{ bulk_form.owner.hidden_tag() }} <!-- security 'csrf' token -->
                    <div class="form-row">
                        <div class="form-group col-12">
                            {{ bulk_form.owner.owners_list.label(class="form-control-label") }}
                            {% if bulk_form.owner.owners_list.errors %}
                            {{ bulk_form.owner.owners_list(class="form-control form-control-lg required is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in bulk_form.owner.owners_list.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                          {% else %}
                            {{ bulk_form.owner.owners_list(class="form-control required from-control-lg") }}
                          {% endif %}
                         </div>
                        <input type="hidden" class="leads_data" name="leads_owner">
                    </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                {{ bulk_form.owner.submit(id="bulk-lead-submit", class="btn btn-primary") }}
            </div>
        </div>
    </div>
     </form>
</div>

crm/templates/leads/filters.html
<form class="form-lead-filter" method="POST">
    {{ filters.hidden_tag() }} <!-- security 'csrf' token -->
    <div class="d-flex flex-column justify-content-between flex-wrap flex-md-nowrap pb-4 mb-3">
        <div class="mb-2"><strong>Filters</strong></div>
        <div class="btn-toolbar mb-2 mb-md-0">
                <div class="col-md-3 pl-0">
                    {{ filters.txt_search(class="form-control from-control-lg", placeholder="search ...") }}
                </div>
                <div class="col-md-3 pl-0">
                    <div class="form-group text-left">
                        {{ filters.lead_source(class="my-select form-control",
                            multiple=True, title="Select Lead Source") }}
                    </div>
                </div>
                <div class="col-md-3 pl-0">
                    <div class="form-group text-left">
                        {{ filters.lead_status(class="my-select form-control",
                            multiple=True, title="Select Lead Status") }}
                    </div>
                </div>
                {% if current_user.role.name == 'admin' %}
                <div class="col-md-3 pl-0">
                    <div class="form-group text-left">
                        {{ filters.assignees(class="my-select form-control") }}
                    </div>
                </div>
                {% endif %}

        </div>
        <div class="btn-toolbar mb-1 mb-md-0">
            {% if current_user.role.name == 'admin' %}
            <div class="col-md-3 pl-0">
                <div class="form-group text-left">
                     {{ filters.advanced_admin(class="my-select form-control") }}
                </div>
            </div>
            {% else %}
            <div class="col-md-3 pl-0">
                <div class="form-group text-left">
                     {{ filters.advanced_user(class="my-select form-control") }}
                </div>
            </div>
            {% endif %}
            <div class="col-md-3 pl-0">
                {{ filters.submit(class="btn btn-md btn-outline-info mr-2") }}
                <a href="{{ url_for('leads.reset_filters') }}" class="btn btn-md btn-outline-secondary" role="button">
                    <span data-feather="x-circle"></span>
                </a>
            </div>
        </div>
    </div>
</form>

crm/templates/leads/leads_list.html
{% extends "layout.html" %}
    {% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2 class="h4">{% if title %}{{title}}{% else %}No Title{% endif %}</h2>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="dropdown">
              <button class="btn btn-sm btn-outline-primary mr-2 dropdown-toggle bulk_assign disabled"
                      type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
                      aria-expanded="false">
                  <span data-feather="settings"></span> Bulk Actions
              </button>
              <div class="dropdown-menu dd-sm" aria-labelledby="dropdownMenuButton">
                  {% if current_user.is_admin %}
                <a class="dropdown-item " href="#" data-toggle="modal" data-target="#leadOwnerAssignModal">Assign Owner</a>
                  <a class="dropdown-item" href="#" data-toggle="modal" data-target="#leadSourceAssignModal">Assign Source</a>
                  <a class="dropdown-item" href="#" data-toggle="modal" data-target="#leadStatusAssignModal">Assign Status</a>
                    <div class="dropdown-divider"></div>
                  <a class="dropdown-item" data-toggle="modal" data-target="#leadsDeleteModal" href="#">Delete</a>
                  <div class="dropdown-divider"></div>
                  {% endif %}
                <a class="dropdown-item" id="export_leads_to_csv" href="#">Export to CSV</a>
              </div>

            </div>
            {% if current_user.is_admin %}
            <a class="btn btn-sm btn-outline-secondary mr-2" role="button" href="{{ url_for('leads.import_bulk_leads') }}">
                <span data-feather="upload"></span>
                  import leads ...
            </a>
            {% endif %}
            <a class="btn btn btn-sm btn-outline-primary" role="button" href="{{ url_for('leads.new_lead') }}">
                <span data-feather="plus"></span>
                  New
            </a>
        </div>
    </div>
    {% include "leads/filters.html" %}
    {% if leads.items()|length > 0 %}
        <div class="table-responsive">
            <table class="table table-striped table-hover fixed-layout-table">
              <thead class="thead-light">
                <tr>
                  <th width="40" scope="col">
                      <input type="checkbox" id="select_all" value="all" />
                  </th>
                    <th width="150"></th>
                    <th width="300" scope="col">Title</th>
                  <th width="150" scope="col">First Name</th>
                  <th width="150" scope="col">Last Name</th>
                  <th width="300" scope="col">Email</th>
                    <th width="250" scope="col">Company Name</th>
                     <th width="150" scope="col">Phone</th>
                     <th width="150" scope="col">Mobile</th>
                    <th width="250" scope="col">Owner</th>
                    <th width="200" scope="col">Lead Source</th>
                     <th width="200" scope="col">Lead Status</th>
                    <th width="200" scope="col">Date Created</th>
                </tr>
              </thead>
              <tbody>
                {% for lead in leads.items() %}
                <tr>
                  <th scope="row">
                      <input class="cb" type="checkbox" value="{{ lead.id }}" />
                  </th>
                    <th>
                        <a href="{{ url_for('leads.update_lead', lead_id=lead.id) }}"
                           class="btn btn-outline-secondary btn-sm mr-1" role="button">
                            <span data-feather="edit"></span>
                        </a>
                        <a href="#" class="btn btn-outline-secondary btn-sm mr-1" role="button">
                            <span data-feather="trash"></span>
                        </a>
                        <a href="{{ url_for('leads.get_lead_view', lead_id=lead.id) }}"
                           class="btn btn-outline-secondary btn-sm mr-1" role="button">
                            <span data-feather="arrow-up-right"></span>
                        </a>
                    </th>
                    <td>{{ lead.title }}</td>
                  <td>{{ lead.first_name }}</td>
                  <td>{{ lead.last_name }}</td>
                    <td>{{ lead.email }}</td>
                    <td>{{ lead.company_name }}</td>
                    <td>{{ lead.phone }}</td>
                    <td>{{ lead.mobile }}</td>
                    <td>{% with owner=lead.owner %}{% include 'common/owner_cell.html' %}{% endwith %}</td>
                    <td>{{ lead.source.source_name }}</td>
                    <td>{{ lead.status.status_name }}</td>
                    <td>{{ lead.date_created.strftime('%Y-%m-%d') if lead.date_created }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>

        <!-- pagination -->
        {% if leads.total_records > 10 %}
            {% with view_id="leads.get_leads_view", items=leads %}
                {% include "common/pagination.html" %}
            {% endwith %}
        {% endif %}
    {% else %}
        <div class="container text-center pt-4">
            <div><span data-feather="eye-off"></span></div>
            <p>No leads found. Please create your first lead.</p>
        </div>
    {%  endif %}
<script>
    $(document).ready(function() {
        var items = [];

        $('#select_all').on('click', function() {
            if ($(this).is(':checked')) {
                $('.cb').prop('checked', true);
            } else {
                $('.cb').prop('checked', false);
            }
            toggle_convert_lead_btn();
        });

        $('.cb').on('click', function() {
            toggle_convert_lead_btn();
        });

        function toggle_convert_lead_btn() {
            items = [];
            $('.cb').each(function() {
                if ($(this).is(':checked')) {
                    items.push($(this).val());
                }
            });

            if (items.length > 0) {
                $('#convert_lead').removeClass('disabled');
                $('.bulk_assign').removeClass('disabled');
            } else {
                $('#convert_lead').addClass('disabled');
                $('.bulk_assign').addClass('disabled');
            }
        }

        $('.ba_modal').on('show.bs.modal', function (e) {
          // do something...
          $('.modal-notif-area').html(`
                <div class="alert alert-success" role="alert">
                  You have selected <strong>${items.length}</strong> leads for bulk assignment.
                </div>`);

          // store the values
          console.log(items);
          $('.leads_data').val(items);
        });

        $('#export_leads_to_csv').on('click', function(e) {
            e.preventDefault();
            window.location = "{{ url_for('leads.write_to_csv') }}?lead_ids=" + items
        });

    });
</script>

<!-- Lead Owner Assign Modal -->
{% include "leads/bulk_owner_assign_modal.html" %}

<!-- Lead Source Assign Modal -->
{% include "leads/bulk_lead_source_assign_modal.html" %}

<!-- Lead Status Assign Modal -->
{% include "leads/bulk_lead_status_assign_modal.html" %}

<!-- Lead Bulk Delete Modal -->
{% include "leads/bulk_lead_delete_modal.html" %}


{% endblock %}